apiVersion: apps/v1
kind: Deployment
metadata:
  name: libraryapp-deployment
  labels:
    app: libraryapp
spec:
  replicas: 2  # On commence avec 2 instances pour la haute disponibilit√©
  selector:
    matchLabels:
      app: libraryapp
  template:
    metadata:
      labels:
        app: libraryapp
    spec:
      containers:
      - name: libraryapp
        image: libraryapp:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
